name: npm publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install Dependencies
        run: npm install

      - name: Build Dist
        run: npm run dist

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JUZI_ADMIN_SCOPE_NPM_TOKEN }}
